# Generated by Django 5.0.4 on 2024-05-14 14:24

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(default=uuid.UUID('2057bdb4-df75-466c-8c44-67f4529a1d89'), max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('procurement_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 14, 24, 58, 180554, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'ordering': ['-procurement_date'],
            },
        ),
    ]
